[build]
  functions = "functions"
  base = "/"
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/api/*"
  to = "https://chanti-dz-backend.herokuapp.com/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}
